CREATE DATABASE IF NOT EXISTS estoque_mercadinho CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE estoque_mercadinho;

CREATE TABLE IF NOT EXISTS funcionarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  login VARCHAR(60) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  perfil ENUM('GERENTE','FUNCIONARIO') NOT NULL DEFAULT 'FUNCIONARIO',
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS produtos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  nome VARCHAR(150) NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  preco DECIMAL(10,2) NOT NULL DEFAULT 0,
  quantidade INT NOT NULL DEFAULT 0,
  limite_minimo INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CHECK (preco >= 0),
  CHECK (quantidade >= 0),
  CHECK (limite_minimo >= 0)
);

CREATE TABLE IF NOT EXISTS movimentacoes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  produto_id INT NOT NULL,
  funcionario_id INT NOT NULL,
  tipo ENUM('ENTRADA','SAIDA') NOT NULL,
  quantidade INT NOT NULL,
  observacao VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_mov_produto FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE RESTRICT,
  CONSTRAINT fk_mov_funcionario FOREIGN KEY (funcionario_id) REFERENCES funcionarios(id) ON DELETE RESTRICT,
  CHECK (quantidade > 0),
  INDEX idx_mov_data (created_at),
  INDEX idx_mov_produto (produto_id)
);


